default: &default
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: omegab.dzikofuentes  # Replace with your system username (e.g., from `whoami`)
  password:  # Leave blank for local dev; set for production
  host: localhost

development:
  <<: *default
  database: cannadex_development

test:
  <<: *default
  database: cannadex_test

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>